baseURL = "https://obenedito.org/"
languageCode = "en-us"
title = "Oscar Benedito"
author = "Oscar Benedito"
paginate = 5

[params]
  blog_title = "Personal blog"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  categories = "/blog/categories/:slug/"
  tags = "/blog/tags/:slug/"

[frontmatter]
  date  = [":filename", ":default"]
