baseURL = "https://obenedito.org/"
languageCode = "en-us"
title = "Oscar Benedito"
paginate = 5
pygmentsStyle = "solarized-dark256"
disableKinds = "taxonomyTerm"

[params]
  blog_title = "Personal blog"
  Author = "Oscar Benedito"
  active_years = ["2020", "2019"]

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  categories = "/blog/categories/:slug/"
  tags = "/blog/tags/:slug/"
  blog_archive = "/blog/archive/"

[frontmatter]
  date  = [":filename", ":default"]
