baseURL = "https://oscarbenedito.com/"
languageCode = "en-us"
title = "Oscar Benedito"
paginate = 5
pygmentsStyle = "solarized-dark256"
disableKinds = "taxonomyTerm"

[Author]
  name = "Oscar Benedito"
  email = "oscar@oscarbenedito.com"

[params]
  domain = "oscarbenedito.com"
  active_years = ["2020", "2019"]

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  categories = "/blog/categories/:slug/"
  tags = "/blog/tags/:slug/"

[frontmatter]
  date  = ["date", ":filename", ":default"]
  lastmod = [":default", ":filename"]

[markup.goldmark.renderer]
  unsafe = true  # This just allows HTML on Markdown, unsafe here just means that if everyone could edit your Markdown, someone could put malicious JS on it.
